### ISSUE TITLE
I don't understand the reason for the error: ProjectValidationError

### ISSUE THREAD

**Issue by tequilaonelove** [formatools/forma#86]
I've been trying to make a module for three hours already.
```
Caused by: com.stepango.forma.error.ProjectValidationError: Project example: name does not match type requirements
Projects of type "LibraryTarget" should contain name suffix "library" 
	at com.stepango.forma.validation.ValidatorKt.throwProjectValidationError(Validator.kt:44)
	at com.stepango.forma.validation.ValidatorKt.validateName(Validator.kt:36)
	at com.stepango.forma.validation.ValidatorKt$validator$1.validate(Validator.kt:26)
	at com.stepango.forma.validation.ValidatorKt.validate(Validator.kt:21)
	at AndroidUtilKt.androidUtil(androidUtil.kt:42)
	at AndroidUtilKt.androidUtil$default(androidUtil.kt:72)
	at Build_gradle.<init>(Unknown Source)
	... 136 more
```
file **build.gradle.kts** in my example-module:
```
plugins {
    id("com.android.library")
    id("kotlin-android")
}

repositories {
    jcenter()
    google()
}

androidLibrary(
    packageName = "com.example",
    dependencies = deps(
        androidxDeps.core,
        androidxDeps.appcompat,
        androidxDeps.material,
        androidxDeps.constraintlayout
    )
)
```
what am I doing wrong? Thanks. :)

**Comment by michaem** [comment]
Hey! Thx for feedback!

Issue reason is that you named module not according to the Form naming rules. The name of the module should contains the suffix "library" and looks like that:

In project gradle settings
`:[your-module]:library`

or it same for directory path
`/your-module/library/build.gradle.kts`

For more information you can look on our app sample https://github.com/formatools/forma/tree/master/application/core/network/library

Best regards,
Michael Emelyanov

**Comment by tequilaonelove** [comment]
Большое спасибо за ваш ответ!
